version: "3.8"
services:
  codenames-frontend:
    restart: always
    build:
     context: frontend
     dockerfile: Dockerfile
    image: codenames-frontend
    stdin_open: true
    container_name: codenames-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app/
    # depends_on:
    #   - 
    command: npm run dev